--- srcs/meta-confidential-compute/conf/distro/cvm.conf	2024-01-01 00:00:00.000000000 +0000
+++ srcs/meta-confidential-compute/conf/distro/cvm.conf	2024-01-01 00:00:00.000000000 +0000
@@ -41,7 +41,7 @@

 require conf/distro/include/yocto-uninative.inc

-PREFERRED_VERSION_linux-yocto-tiny ?= "6.6%"
+PREFERRED_VERSION_linux-yocto-tiny ?= "6.8%"

 # Disable polkit's systemd configuration.
 PACKAGECONFIG:remove:pn-polkit = "systemd"
